version: '2'

services:

  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "1812:1812/udp"
    environment:
      - AAA_SECRET_KEY=FunnyTreeBlackDeceive1
      - DEBUG=authorization*
      - MONGO=localhost:27017/radius-dev
      - NODE_ENV=development

  acct:
    build:
      context: .
      dockerfile: Dockerfile.acct
    ports:
      - "1813:1813/udp"
    environment:
      - AAA_SECRET_KEY=FunnyTreeBlackDeceive1
      - AD_HOST=manager-api-dev.tideanalytics.com
      - AD_KEY=DuS6YR9aCMJc0345mPNAkAIzaSyCChtVm4UlxD4
      - DEBUG=accounting*
      - MONGO=localhost:27017/radius-dev
      - NODE_ENV=development

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - API_TOKEN=uVJ6t7bvRSQa3qaNKLLfyGwtrdqce9RI
      - API_PORT=3000
      - DEBUG=api*
      - MONGO=localhost:27017/radius-dev
      - NODE_ENV=development

  # database:
  #   ports:
  #     - "27017:27017"
  #   image: mongo:3.4
