version: '2'

services:

  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "1812:1812/udp"
    environment:
      - DEBUG=authorization*,admanager
      - MONGO=
      - NODE_ENV=development
      - SECRET_KEY=

  acct:
    build:
      context: .
      dockerfile: Dockerfile.acct
    ports:
      - "1813:1813/udp"
    environment:
      - AD_HOST=
      - AD_KEY=
      - DEBUG=accounting*,admanager
      - MONGO=
      - NODE_ENV=development
      - SECRET_KEY=
