version: '2'

services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - API_TOKEN=uVJ6t7bvRSQa3qaNKLLfyGwtrdqce9RI
      - DEBUG=web:*
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - MONGO_DATABASE=radius
      - NODE_ENV=staging
      - PORT=3001
      - SECRET_KEY=mikrotiksecret
      - BOOTSTRAP=true

  database:
    ports:
      - "27017:27017"
    image: mongo:3.4
