version: '2'

services:

  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "1812:1812/udp"
    environment:
      - DEBUG=authorization*,admanager
      - MONGO=localhost:27017/radius-dev
      - NODE_ENV=development
      - SECRET_KEY=FunnyTreeBlackDeceive1

  acct:
    build:
      context: .
      dockerfile: Dockerfile.acct
    ports:
      - "1813:1813/udp"
    environment:
      - AD_HOST=manager-api-dev.tideanalytics.com
      - AD_KEY=DuS6YR9aCMJc0345mPNAkAIzaSyCChtVm4UlxD4
      - DEBUG=accounting*,admanager
      - MONGO=localhost:27017/radius-dev
      - NODE_ENV=development
      - SECRET_KEY=FunnyTreeBlackDeceive1
