version: '2'

services:

  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "1812:1812/udp"
    environment:
      - AAA_SECRET_KEY=mikrotiksecret
      - DEBUG=auth:*
      - MONGO_USER=radius-user
      - MONGO_PASS=radius-punya-password
      - MONGO_HOST=192.168.0.132
      - MONGO_PORT=27017
      - MONGO_DB=radius
      - NODE_ENV=staging

  acct:
    build:
      context: .
      dockerfile: Dockerfile.acct
    ports:
      - "1813:1813/udp"
    environment:
      - AAA_SECRET_KEY=mikrotiksecret
      - DEBUG=acct:*
      - MONGO_USER=radius-user
      - MONGO_PASS=radius-punya-password
      - MONGO_HOST=192.168.0.132
      - MONGO_PORT=27017
      - MONGO_DB=radius
      - NODE_ENV=staging

  wapi:
    build:
      context: .
      dockerfile: Dockerfile.wapi
    ports:
      - "3001:3001"
    environment:
      - DEBUG=wapi:*
      - MONGO_USER=radius-user
      - MONGO_PASS=radius-punya-password
      - MONGO_HOST=192.168.0.132
      - MONGO_PORT=27017
      - MONGO_DB=radius
      - NODE_ENV=staging
      - WEB_API_TOKEN=uVJ6t7bvRSQa3qaNKLLfyGwtrdqce9RI
      - WEB_PORT=3001

  # boot:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.bootstrap
  #   volumes:
  #    - .:/app
  #   environment:
  #     - DEBUG=boot
  #     - MONGO_USER=radius-user
  #     - MONGO_PASS=radius-punya-password
  #     - MONGO_HOST=192.168.0.132
  #     - MONGO_PORT=27017
  #     - MONGO_DB=radius
  #     - NODE_ENV=staging

  # database:
  #   ports:
  #     - "27017:27017"
  #   image: mongo:3.4
